name: Test and publish the package on release

on:
  release:
    types: [published]

jobs:
  test:
    name: Test the package
    uses: ./.github/workflows/_test.yaml
    with:
      python-version: '3.10'
  publish:
    name: Publish the package
    needs: test
    uses: ./.github/workflows/_publish.yaml
    with:
      release-version: ${{ github.ref_name }}
